config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'dashboard' => 'dashboard#index'
  post 'token/generate' => 'token#generate'
  post 'call/connect' => 'call#connect'

  resources :tickets, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :name, :phone_number, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/call_controller.rb
class CallController < ApplicationController
  skip_before_action :verify_authenticity_token

  def connect
    render xml: twilio_reponse
  end

  private

  def twilio_reponse
    twilio_number = ENV['TWILIO_PHONE_NUMBER']
    res = Twilio::TwiML::VoiceResponse.new do |response|
      dial = Twilio::TwiML::Dial.new caller_id: twilio_number

      if params.include?(:phoneNumber)
        dial.number params[:phoneNumber]
      else
        dial.client(identity: 'support_agent')
      end
      response.append(dial)
    end
    return res.to_s
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @tickets = Ticket.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def create
    support_ticket = Ticket.new(ticket_params)

    if support_ticket.save
      redirect_to root_path, notice:
        'Your ticket was submitted! An agent will call you soon.'
    else
      redirect_to root_path, flash:
        { error: support_ticket.errors.full_messages }
    end
  end

  def ticket_params
    params.require(:ticket).permit(:name, :phone_number, :description)
  end
end

app/controllers/token_controller.rb
# frozen_string_literal: true

require 'twilio_access_token'

class TokenController < ApplicationController
  skip_before_action :verify_authenticity_token

  def generate
    token = ::TwilioAccessToken.generate(role)
    render json: { token: token }
  end

  def role
    params[:page] == dashboard_path ? 'support_agent' : 'customer'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.erb
<h2>Support Tickets</h2>

<p class="lead">
This is the list of most recent support tickets. Click the "Call customer" button to start a phone call from your browser.
</p>

<div class="row">
  <div class="col-md-4 col-md-push-8">
    <div class="panel panel-primary client-controls">
      <div class="panel-heading">
        <h3 class="panel-title">Make a call</h3>
      </div>
      <div class="panel-body">
        <p><strong>Status</strong></p>
        <div class="well well-sm" id="call-status">
          Connecting to Twilio...
        </div>

        <button class="btn btn-lg btn-success answer-button" disabled>Answer call</button>
        <button class="btn btn-lg btn-danger hangup-button" disabled onclick="hangUp()">Hang up</button>
      </div>
    </div>
  </div>

  <div class="col-md-8 col-md-pull-4">
    <% @tickets.each do |ticket| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Ticket #<%= ticket.id %>  <small class="pull-right"><%= ticket.created_at %></small></h3>
      </div>

      <div class="panel-body">

        <div class="pull-right">
          <button onclick="callCustomer('<%= ticket.phone_number %>')" type="button" class="btn btn-primary btn-lg call-customer-button">
            <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
            Call customer
          </button>
        </div>

        <p><strong>Name:</strong> <%= ticket.name %></p>
        <p><strong>Phone number:</strong> <%= ticket.phone_number %></p>
        <p><strong>Description:</strong></p>
        <%= ticket.description %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/home/index.erb
<!-- Main jumbotron -->
<div class="jumbotron bicycle-polo-background">
  <div class="container bicycle-polo-text">
    <h1 class="text-center"><strong>Birchwood Bicycle Polo Co.</strong></h1>
    <p>
    We sell only the finest bicycle polo supplies for those seeking fame and glory in this <a href="https://www.youtube.com/watch?v=DaK9Zj3QHDY" target="_blank">sport of kings</a>.
    </p>

    <h3><strong>Having trouble with one of our products?</strong></h3>
    <p>
    Talk to one of our support agents now — or fill out the support form below and someone will call you later.
    </p>
    <p><a class="btn btn-primary btn-lg btn-block" href="#support" role="button">Get help</a></p>
  </div>
</div>

<div class="container">
  <%= render partial: 'shared/messages' %>

  <h2 id="support">Contact support</h2>

  <p class="lead">
  Talk with one of our support agents right now by clicking the "Call Support" button on the right. If you can't talk now, fill out a support ticket and an agent will call you later.
  </p>

  <div class="row">

    <div class="col-md-6 col-md-push-6">

      <div class="panel panel-info client-controls">
        <div class="panel-heading">
          <h3 class="panel-title">Talk to support now</h3>
        </div>
        <div class="panel-body">
          <p><strong>Status</strong></p>
          <div class="well well-sm" id="call-status">
            Connecting to Twilio...
          </div>

          <button class="btn btn-lg btn-primary call-support-button" onclick="callSupport()">
            <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> Call support
          </button>
          <button class="btn btn-lg btn-danger hangup-button" disabled onclick="hangUp()">Hang up</button>
        </div>
      </div>

    </div>

    <div class="col-md-6 col-md-pull-6">

      <%= form_for :ticket, url: tickets_path do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      <div class="form-group">
          <%= f.label :phone_number, "Phone Number" %>
          <%= f.text_field :phone_number, class: "form-control" %>
      </div>
      <div class="form-group">
          <%= f.label :description, "Description" %>
          <%= f.text_field :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit ticket", class: "btn btn-primary btn-lg btn-block" %>
      </div>
      <% end %>
    </div>
  </div>

  <small class="pull-right">
    Header photo courtesy <a href="https://www.flickr.com/photos/tink20seven/4654348885/">David Sachs via Flickr</a>
  </small>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Browser Calls</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- CSS -->
  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" %>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Birchwood Bicycle Polo Co.</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= dashboard_path %>">Support dashboard</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      <%= yield %>
      <footer>
        <p>&copy; Your Company <%= Time.now.year %></p>
      </footer>

    </div> <!-- /container -->
    <%= javascript_include_tag "//code.jquery.com/jquery-3.3.1.min.js" %>
    <%= javascript_include_tag "//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" %>
    <%= javascript_include_tag "//media.twiliocdn.com/sdk/js/client/releases/1.7.7/twilio.min.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/shared/_messages.erb
<% if flash[:error] %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <% flash[:error].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %>
  </div>
<% end %>